site_name: invoke-tasklib
site_url: "https://durandtibo.github.io/invoke-tasklib/"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.code.select
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - get_started.md
  - User Guide:
      - uguide/index.md
      - uguide/format.md
      - uguide/lint.md
      - uguide/types.md
      - uguide/test.md
      - uguide/env.md
      - uguide/release.md
      - uguide/doc.md
      - uguide/security.md
      - uguide/clean.md
      - uguide/config.md
  - troubleshooting.md
  - Developer Guide:
      - dev/development.md
      - dev/architecture.md
  - Reference:
      - refs/format.md
      - refs/lint.md
      - refs/types.md
      - refs/test.md
      - refs/env.md
      - refs/release.md
      - refs/doc.md
      - refs/security.md
      - refs/clean.md
      - refs/config.md
  - GitHub: https://github.com/durandtibo/invoke-tasklib

repo_url: https://github.com/durandtibo/invoke-tasklib
repo_name: durandtibo/invoke-tasklib

markdown_extensions:
  - admonition
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../src]
          options:
            allow_inspection: true
            docstring_style: google
            separate_signature: true
            show_bases: true
            show_object_full_path: true
            show_root_full_path: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature: true
            show_signature_annotations: true
            show_source: false
            signature_crossrefs: true

extra:
  version:
    method: mike

copyright: Copyright &copy; 2025 - present Thibaut Durand
